Fix GSM extension issues with numpy 1.16.0rc1
Since numpy 1.16.0rc1, the building of the GSM numpy extension
during installation of the package fails.  CAM does pip installs
with the `--pre` option, so we get this pre-release version.

There were two issues:
- If an older version of numpy is installed (e.g. 1.15.4), and
  then the installation is done, it pulls in 1.16.0rc1, and the
  building of the extension fails, reporting
  ```
  gfortran: error: unrecognized command line option ‘-std=legacy -ffixed-line-length-0’
  ```
  This is fixed by changing the extra args to a list with multiple items.
  This change also works with older versions of numpy (tried 1.14.x and 1.15.x)
- Using 1.16.0rc1 to build the extension results in this error:
  ```
      File "/home/kat/venv_numpy/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
        assert not f, repr((f, line, l))
    AssertionError: (-1, 'nmax=10000) ! increased from 500 by ma', 'nmax=10000) ! increased from 500 by ma')
  ```
  Moving the comment to the next line fixes it.  This may be an f2py bug in the
  pre-release version, but easy enough to work around.